# Generated by Django 4.2.3 on 2023-07-29 17:49

import api.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='applicant', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('job_title', models.CharField(default='Undefined Job', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='expert', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('domaine_expertise', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('idTicket', models.CharField(default=api.models.generate_unique_code, max_length=15, primary_key=True, serialize=False)),
                ('priority', models.IntegerField(help_text='Enter an integer value not exceeding 3.', validators=[django.core.validators.MaxValueValidator(3)])),
                ('etat', models.BooleanField(default=False)),
                ('issue', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('applicantId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='api.applicant')),
                ('expertId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='api.expert')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('idMessage', models.CharField(default=api.models.generate_unique_code, max_length=15, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=800)),
                ('idTicket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.ticket')),
            ],
        ),
    ]
