# Generated by Django 4.2.3 on 2023-08-11 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='state',
        ),
    ]
