# Generated by Django 4.2.3 on 2023-08-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_ticket_expertid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='etat',
            field=models.CharField(default='waiting', max_length=20),
        ),
    ]
