# Generated by Django 4.2.3 on 2023-08-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_ticket_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
