# Generated by Django 4.2.3 on 2023-08-06 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_ticket_creationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
