# Generated by Django 4.2.3 on 2023-08-06 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_message_creationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='source',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
